# hash:sha256:fbdbfe67b1b38a69eacd049d9691edbed0623957bb3544febf859af73a532410
FROM registry.codeocean.com/codeocean/miniconda3:4.8.2-python3.8-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install -U --no-cache-dir \
    anytree==2.8.0 \
    descartes==1.1.0 \
    matplotlib==3.2.1 \
    numpy==1.19.4 \
    scipy==1.5.4 \
    shapely==1.7.1
